// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotatryhard.Data;

#nullable disable

namespace dotatryhard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241127115025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("dotatryhard.Models.Match", b =>
                {
                    b.Property<long>("match_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("match_id"));

                    b.Property<string>("cluster")
                        .HasColumnType("longtext");

                    b.Property<short?>("dire_score")
                        .HasColumnType("smallint");

                    b.Property<short?>("duration")
                        .HasColumnType("smallint");

                    b.Property<short?>("radiant_score")
                        .HasColumnType("smallint");

                    b.Property<long?>("start_time")
                        .HasColumnType("bigint");

                    b.HasKey("match_id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("dotatryhard.Models.Player", b =>
                {
                    b.Property<long>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("account_id"));

                    b.Property<string>("AvatarFull")
                        .HasColumnType("longtext");

                    b.Property<string>("LocCountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("PersonaName")
                        .HasColumnType("longtext");

                    b.HasKey("account_id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dotatryhard.Models.PlayersMatches", b =>
                {
                    b.Property<long>("account_id")
                        .HasColumnType("bigint");

                    b.Property<long>("match_id")
                        .HasColumnType("bigint");

                    b.Property<short?>("assists")
                        .HasColumnType("smallint");

                    b.Property<short?>("deaths")
                        .HasColumnType("smallint");

                    b.Property<short?>("gold_per_min")
                        .HasColumnType("smallint");

                    b.Property<short?>("kills")
                        .HasColumnType("smallint");

                    b.Property<long>("match_id1")
                        .HasColumnType("bigint");

                    b.Property<long>("playeraccount_id")
                        .HasColumnType("bigint");

                    b.Property<short?>("xp_per_min")
                        .HasColumnType("smallint");

                    b.HasKey("account_id", "match_id");

                    b.HasIndex("match_id1");

                    b.HasIndex("playeraccount_id");

                    b.ToTable("PlayersMatches");
                });

            modelBuilder.Entity("dotatryhard.Models.PlayersMatches", b =>
                {
                    b.HasOne("dotatryhard.Models.Match", "match")
                        .WithMany("PlayersMatches")
                        .HasForeignKey("match_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotatryhard.Models.Player", "player")
                        .WithMany("PlayersMatches")
                        .HasForeignKey("playeraccount_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("match");

                    b.Navigation("player");
                });

            modelBuilder.Entity("dotatryhard.Models.Match", b =>
                {
                    b.Navigation("PlayersMatches");
                });

            modelBuilder.Entity("dotatryhard.Models.Player", b =>
                {
                    b.Navigation("PlayersMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
