// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotatryhard.Data;

#nullable disable

namespace dotatryhard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("dotatryhard.Models.Match", b =>
                {
                    b.Property<long>("match_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("match_id"));

                    b.Property<int?>("cluster")
                        .HasColumnType("int");

                    b.Property<short?>("dire_score")
                        .HasColumnType("smallint");

                    b.Property<short?>("duration")
                        .HasColumnType("smallint");

                    b.Property<long?>("match_seq_num")
                        .HasColumnType("bigint");

                    b.Property<short?>("radiant_score")
                        .HasColumnType("smallint");

                    b.Property<bool>("radiant_win")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("start_time")
                        .HasColumnType("bigint");

                    b.HasKey("match_id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("dotatryhard.Models.Player", b =>
                {
                    b.Property<long>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("account_id"));

                    b.Property<string>("avatarfull")
                        .HasColumnType("longtext");

                    b.Property<string>("loccountrycode")
                        .HasColumnType("longtext");

                    b.Property<string>("personaname")
                        .HasColumnType("longtext");

                    b.HasKey("account_id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dotatryhard.Models.PlayersMatches", b =>
                {
                    b.Property<long>("match_id")
                        .HasColumnType("bigint");

                    b.Property<long>("account_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("ability_0")
                        .HasColumnType("int");

                    b.Property<int?>("ability_1")
                        .HasColumnType("int");

                    b.Property<int?>("ability_2")
                        .HasColumnType("int");

                    b.Property<int?>("ability_3")
                        .HasColumnType("int");

                    b.Property<byte?>("aghanims_scepter")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short?>("aghanims_shard")
                        .HasColumnType("smallint");

                    b.Property<short?>("assists")
                        .HasColumnType("smallint");

                    b.Property<short?>("backpack_0")
                        .HasColumnType("smallint");

                    b.Property<short?>("backpack_1")
                        .HasColumnType("smallint");

                    b.Property<short?>("backpack_2")
                        .HasColumnType("smallint");

                    b.Property<short?>("deaths")
                        .HasColumnType("smallint");

                    b.Property<short?>("denies")
                        .HasColumnType("smallint");

                    b.Property<short?>("gold_per_min")
                        .HasColumnType("smallint");

                    b.Property<int?>("hero_damage")
                        .HasColumnType("int");

                    b.Property<int?>("hero_healing")
                        .HasColumnType("int");

                    b.Property<short?>("hero_id")
                        .HasColumnType("smallint");

                    b.Property<short?>("hero_level")
                        .HasColumnType("smallint");

                    b.Property<short?>("item_0")
                        .HasColumnType("smallint");

                    b.Property<short?>("item_1")
                        .HasColumnType("smallint");

                    b.Property<short?>("item_2")
                        .HasColumnType("smallint");

                    b.Property<short?>("item_3")
                        .HasColumnType("smallint");

                    b.Property<short?>("item_4")
                        .HasColumnType("smallint");

                    b.Property<short?>("item_5")
                        .HasColumnType("smallint");

                    b.Property<short?>("item_neutral")
                        .HasColumnType("smallint");

                    b.Property<short?>("kills")
                        .HasColumnType("smallint");

                    b.Property<short?>("last_hits")
                        .HasColumnType("smallint");

                    b.Property<byte?>("leaver_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("moonshard")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("net_worth")
                        .HasColumnType("int");

                    b.Property<short?>("player_slot")
                        .HasColumnType("smallint");

                    b.Property<byte?>("team")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("tower_damage")
                        .HasColumnType("int");

                    b.Property<byte>("win")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short?>("xp_per_min")
                        .HasColumnType("smallint");

                    b.HasKey("match_id", "account_id");

                    b.HasIndex("account_id");

                    b.ToTable("PlayersMatches");
                });

            modelBuilder.Entity("dotatryhard.Models.PlayersMatchesAverages", b =>
                {
                    b.Property<long>("account_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("aghanims_scepter")
                        .HasColumnType("int");

                    b.Property<int?>("aghanims_shard")
                        .HasColumnType("int");

                    b.Property<int?>("assists")
                        .HasColumnType("int");

                    b.Property<int?>("deaths")
                        .HasColumnType("int");

                    b.Property<int?>("denies")
                        .HasColumnType("int");

                    b.Property<int?>("gold_per_min")
                        .HasColumnType("int");

                    b.Property<int?>("hero_damage")
                        .HasColumnType("int");

                    b.Property<int?>("hero_healing")
                        .HasColumnType("int");

                    b.Property<int?>("hero_level")
                        .HasColumnType("int");

                    b.Property<int?>("kills")
                        .HasColumnType("int");

                    b.Property<int?>("last_hits")
                        .HasColumnType("int");

                    b.Property<int?>("leaver_status")
                        .HasColumnType("int");

                    b.Property<int?>("match_count")
                        .HasColumnType("int");

                    b.Property<long?>("match_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("moonshard")
                        .HasColumnType("int");

                    b.Property<int?>("net_worth")
                        .HasColumnType("int");

                    b.Property<int?>("tower_damage")
                        .HasColumnType("int");

                    b.Property<int?>("win")
                        .HasColumnType("int");

                    b.Property<int?>("xp_per_min")
                        .HasColumnType("int");

                    b.HasKey("account_id");

                    b.HasIndex("match_id");

                    b.ToTable("PlayersMatchesAverages");
                });

            modelBuilder.Entity("dotatryhard.Models.PlayersMatches", b =>
                {
                    b.HasOne("dotatryhard.Models.Player", "player")
                        .WithMany("PlayersMatches")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotatryhard.Models.Match", "match")
                        .WithMany("PlayersMatches")
                        .HasForeignKey("match_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("match");

                    b.Navigation("player");
                });

            modelBuilder.Entity("dotatryhard.Models.PlayersMatchesAverages", b =>
                {
                    b.HasOne("dotatryhard.Models.Player", "player")
                        .WithMany("PlayersMatchesAverages")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotatryhard.Models.Match", null)
                        .WithMany("PlayersMatchesAverages")
                        .HasForeignKey("match_id");

                    b.Navigation("player");
                });

            modelBuilder.Entity("dotatryhard.Models.Match", b =>
                {
                    b.Navigation("PlayersMatches");

                    b.Navigation("PlayersMatchesAverages");
                });

            modelBuilder.Entity("dotatryhard.Models.Player", b =>
                {
                    b.Navigation("PlayersMatches");

                    b.Navigation("PlayersMatchesAverages");
                });
#pragma warning restore 612, 618
        }
    }
}
